name: flutter_vanilla_todos
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.2
  hive_flutter: ^1.1.0
  uuid: ^3.0.6

dev_dependencies:
  build_runner: ^2.1.11
  flutter_lints: ^2.0.0
  hive_generator: ^1.1.3

flutter:
  uses-material-design: true
